$background = rgba({{colors.background.default.hex_stripped}}ff)
$source_color = rgba({{colors.source_color.default.hex_stripped}}ff)
$primary = rgba({{colors.primary.default.hex_stripped}}ff)
$secondary = rgba({{colors.secondary.default.hex_stripped}}ff)
$on_secondary_container = rgba({{colors.on_secondary_container.default.hex_stripped}}ff)
$on_surface = rgba({{colors.on_surface.default.hex_stripped}}ff)
$surface_container = rgba({{colors.surface_container.default.hex_stripped}}ff)
$color8 = rgba({{colors.outline.default.hex_stripped}}ff)
