[config.wallpaper]
command = "swww"
arguments = ["img", "--transition-type", "any", "--transition-fps", "60", "--transition-duration", "0.5"]
set = true

[templates.waybar]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = '~/.config/hypr/scripts/matugen-waybar-posthook.sh'

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty-colors.conf'
output_path = '~/.config/kitty/theme.conf'
post_hook = "kill -SIGUSR1 $(pidof kitty)"

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland-colors.conf'
output_path = '~/.config/hypr/colors.conf'
post_hook = 'hyprctl reload'

[templates.hyprlock]
input_path = '~/.config/matugen/templates/hyprlock-colors.conf'
output_path = '~/.config/hypr/hyprlock_colors.conf'

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/colors.css'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/colors.css'

[templates.rofi]
input_path = '~/.config/matugen/templates/rofi-colors.rasi'
output_path = '~/.config/rofi/colors.rasi'

[templates.dunst]
input_path = '~/.config/matugen/templates/dunst-colors'
output_path = '~/.config/dunst/dunstrc_colors'
post_hook = "killall dunst ; dunst &"

[templates.fastfetch]
input_path = '~/.config/matugen/templates/fastfetch-config.jsonc'
output_path = '~/.config/fastfetch/config.jsonc'
post_hook = '~/.config/hypr/scripts/update-fastfetch-colors.sh'
